#!/usr/bin/env bash
# Renders THIRD_PARTY_NOTICES.md: every Rust crate and npm package that ships
# inside a ContractorCRM build, with its license and project URL.
#
# Tooling choice: cargo-license + license-checker-rseidelsohn, not cargo-about.
# cargo-about needs a checked-in about.toml plus a handlebars template and
# fails the whole run on any crate whose license string it cannot classify --
# a dependency bump would then break a release build. The two JSON emitters
# here need no config, never fail on an odd license string (they print it
# verbatim), and cover both halves of the app; this script does the rendering.
#
# Usage: scripts/generate-notices.sh [output-path]
#        (default output: THIRD_PARTY_NOTICES.md in the repo root)
#
# Requires: jq, npx, and cargo-license (cargo install cargo-license).
set -euo pipefail

repo_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
output="${1:-${repo_dir}/THIRD_PARTY_NOTICES.md}"

for tool in jq npx cargo; do
  if ! command -v "${tool}" >/dev/null 2>&1; then
    echo "generate-notices: ${tool} is required but not on PATH" >&2
    exit 1
  fi
done

if ! cargo license --help >/dev/null 2>&1; then
  echo "generate-notices: cargo-license missing (cargo install cargo-license)" >&2
  exit 1
fi

work_dir="$(mktemp -d)"
trap 'rm -rf "${work_dir}"' EXIT

# Rust: runtime dependencies only. Dev-dependencies (test harnesses) and
# build-dependencies never end up in a shipped binary.
echo "==> collecting Rust crate licenses"
cargo license \
  --manifest-path "${repo_dir}/src-tauri/Cargo.toml" \
  --avoid-dev-deps \
  --avoid-build-deps \
  --json >"${work_dir}/rust.json"

# npm: production dependencies only, for the same reason.
echo "==> collecting npm package licenses"
(cd "${repo_dir}" && npx --yes license-checker-rseidelsohn \
  --production \
  --json \
  --excludePrivatePackages) >"${work_dir}/npm.json"

app_version="$(jq -r '.version' "${repo_dir}/package.json")"

echo "==> rendering ${output}"
{
  printf '# Third-party notices\n\n'
  printf 'ContractorCRM %s bundles the open-source components listed below.\n' "${app_version}"
  printf 'Each remains under its own license; this file is the attribution\n'
  printf 'notice that ships with every release artifact.\n\n'
  # shellcheck disable=SC2016 # markdown backticks, not a command substitution
  printf 'Generated by `scripts/generate-notices.sh` (cargo-license +\n'
  printf 'license-checker-rseidelsohn). Regenerate it rather than editing it.\n\n'

  rust_count="$(jq 'length' "${work_dir}/rust.json")"
  printf '## Rust crates (%s)\n\n' "${rust_count}"
  printf '| Crate | Version | License | Source |\n'
  printf '| --- | --- | --- | --- |\n'
  jq -r '
    sort_by(.name | ascii_downcase)[]
    | [
        .name,
        .version,
        (.license // "unspecified"),
        (.repository // "")
      ]
    | @tsv
  ' "${work_dir}/rust.json" |
    while IFS=$'\t' read -r name version license repository; do
      printf '| %s | %s | %s | %s |\n' "${name}" "${version}" "${license}" "${repository}"
    done

  npm_count="$(jq 'length' "${work_dir}/npm.json")"
  printf '\n## npm packages (%s)\n\n' "${npm_count}"
  printf '| Package | License | Source |\n'
  printf '| --- | --- | --- |\n'
  jq -r '
    to_entries
    | sort_by(.key | ascii_downcase)[]
    | [
        .key,
        (.value.licenses | if type == "array" then join(" / ") else . end),
        (.value.repository // "")
      ]
    | @tsv
  ' "${work_dir}/npm.json" |
    while IFS=$'\t' read -r name license repository; do
      printf '| %s | %s | %s |\n' "${name}" "${license}" "${repository}"
    done
} >"${output}"

echo "==> wrote ${output}"
